### ISSUE TITLE
adds key to the input if schema key is an object or array.

### ISSUE THREAD

**Issue by chirag04** [mohsen1/deep_pick#1]
Consider the case:

`_.deepPick({a:1, x:1}, {a:1, b: {c:1}});`

returns `Object {a: 1, b: Object}`

b should not be part of the input after this.

**Comment by mohsen1** [comment]
interesting! could you work on a PR for this? I don't have time to work on it at the moment

**Comment by chirag04** [comment]
@mohsen1  done!

Thanks for this module. Saved time for me.

**Comment by chirag04** [comment]
can you merge and publish the latest to npm?

**Comment by mohsen1** [comment]
@chirag04 Done. pushed to npm. Thanks!

**Comment by chirag04** [comment]
:+1:
